Fix testcode
yshici/rspec_app_exam pull request #1
Opened 2020-08-31 10:30 UTC by yshici

以下の通り修正しました。

**TODO**
`:project, :task, :task_done`を`let`で定義。
（`:task_done`は`status: :done`をtraitで設定。）

**FIXME**
・'Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること'
　'View Todos'ボタンクリック後、ウィンドウの遷移動作を追加。

・'Taskを編集した場合、一覧画面で編集後の内容が表示されること'
　探索する日時の表記をヘルパーメソッドを用いて修正。

・'Taskが削除されること'
　`task.title`を`'.task_list'`内で検証するよう修正。

<img width="734" alt="実行結果 2020-08-31 19 27 35" src="https://user-images.githubusercontent.com/67688811/91711087-44476800-ebc0-11ea-8f30-8acebfba86c0.png">

2020-08-31 13:21 UTC, yuji91 requested changes

2020-08-31 13:21 UTC, yuji91 commented on spec/factories/tasks.rb
> +      status { 2 }
2だと何を示しているのか分からないのでSymbolで記載してください
```suggestion
      status { :done }
```

2020-08-31 13:21 UTC, yuji91 commented on spec/system/task_spec.rb
> +include ApplicationHelper
ここでincludeせずに設定ファイルに記載して、ファイル全体で読み込むようにしましょう。

2020-08-31 13:21 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task_done){ FactoryBot.create(:task, :done, project_id: project.id) }
`FactoryBot.`の記載は省略してください。

2020-08-31 13:21 UTC, yuji91 commented on spec/system/task_spec.rb
> +        switch_to_window windows[1]
ここは難しく作ったつもりでしたが、簡単だったでしょうか？

2020-08-31 13:21 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content(Time.current.strftime("%-m/%d %H:%M"))
strftimeのフォーマットを編集したのはどのような意図がありますか？
コミットメッセージに記載されていると分かりやすいです。

2020-08-31 13:21 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task
`let!(:task)`を定義してテストケース実行前にFactoryを作るのもありです。

2020-08-31 13:22 UTC, yuji91 requested changes
指摘事項の修正は1内容につき1コミット毎に分けてください。

2020-08-31 15:32 UTC, yshici commented on spec/factories/tasks.rb
> +      status { 2 }
Symbolで記載しました。
d17a4ee

2020-08-31 15:36 UTC, yshici commented on spec/system/task_spec.rb
> +include ApplicationHelper
rails_helper.rbで読み込むように修正しました。
691429d

2020-08-31 15:42 UTC, yshici commented on spec/system/task_spec.rb
> +  let(:task_done){ FactoryBot.create(:task, :done, project_id: project.id) }
FactoryBot.の記載を省略しました。
b34bfc5

2020-08-31 15:45 UTC, yshici commented on spec/system/task_spec.rb
> +        switch_to_window windows[1]
コード見るだけだとわかりませんでしたが、
実際にアプリ動かしてみると原因わかりました。

2020-08-31 15:49 UTC, yshici commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content(Time.current.strftime("%-m/%d %H:%M"))
この部分、意図せず変更していました。（恐らくFIXME部分の作業中に）
元データに修正しました。
215ffa3

2020-08-31 15:49 UTC, yshici commented on spec/system/task_spec.rb
> +        task
そちらの書き方も頭に入れておきます！

2020-09-01 02:39 UTC, yuji91 requested changes

2020-09-01 02:39 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task_done){ create(:task, :done, project_id: project.id) }
taskのFactoryにassociationを定義するとproject_idを毎回定義する必要が無くなります！

2020-09-02 05:54 UTC, yshici commented on spec/system/task_spec.rb
> +  let(:task_done){ create(:task, :done, project_id: project.id) }
Factoryにassociationを定義しました。
38b8296

2020-09-02 06:04 UTC, merged